version: '3.8'

services:
  jenkins:
    container_name: jenkins
    restart: always
    image: jenkins/jenkins:lts
    tty: true
    ports:
      - 8080:8080
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    container_name: mysql
    restart: always
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jenkins
      MYSQL_USER: devops
      MYSQL_PASSWORD: devops
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  python:
    container_name: python
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8888:8888"
    volumes:
    - ./project:/code
    links:
      - mysql
volumes:
  jenkins-home:
  mysql-data:
